response = input("Enter some text: ")
response = response.replace("a", "4")
response = response.replace("b", "8")
response = response.replace("e", "3")
response = response.replace("l", "1")
response = response.replace("o", "0")
response = response.replace("s", "5")
response = response.replace("t", "7")
print(response)