prompt = input("Enter some text: ")
prompt = prompt.replace("a", "4")
prompt = prompt.replace("b", "8")
prompt = prompt.replace("e", "3")
prompt = prompt.replace("l", "1")
prompt = prompt.replace("o", "0")
prompt = prompt.replace("s", "5")
prompt = prompt.replace("t", "7")
print(prompt)